language: python
python:
  - 3.5
  - 3.6
before_install:
  - python --version
  - python -m unittest
install:
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
script: test.py # run tests
after_success:
  - codecov # submit coverage
