# -*- coding: utf-8 -*-
"""get_movies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pB0FnH9WZ7qlSNjFZmhCKvYMgFAegMp6
"""

import pprint
import time

import pandas as pd
import tmdbsimple as tmdb
from requests.exceptions import HTTPError

pp = pprint

tmdb.API_KEY = '38dd5c6c01713ef99903275d51e2fd68'

# Get last id
last_movie = tmdb.Movies('latest')
last_movie.info(language="es-ES")
last_id = last_movie.id

# Create empty dataframe
films = pd.DataFrame(columns=['id', 'original_title', 'title', 'overview', 'genres', 'cast', 'crew', 'release_date'])


def get_all_info(movie_id):
    movie = tmdb.Movies(movie_id)

    def movie_request(movie):

        movie.info(language="es-ES")
        cast = movie.credits()['cast']
        crew = movie.credits()['crew']

        return movie.id, movie.original_title, movie.title, movie.overview, movie.genres, cast, crew, movie.release_date

    try:

        return movie_request(movie)

    except HTTPError as err:

        # print(err.response.status_code)
        if err.response.status_code == 429:

            time.sleep(10)
            try:
                return movie_request(movie)
            except:
                return movie_id, 'original_title', 'title', 'overview', 'genres', 'cast', 'crew', 'release_date'

        else:

            return movie_id, 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'

    except:

        print('Fallo en: ' + str(movie_id))


for i in range(10000, 600001, 10000):
    films = pd.concat([pd.DataFrame([get_all_info(j)], columns=films.columns) for j in range(i)], ignore_index=True)
    films.to_csv('data/movies/movies_'+str(i)+'.csv', sep='|', encoding='utf-8', header=True, index=False)
    films = pd.DataFrame(
        columns=['id', 'original_title', 'title', 'overview', 'genres', 'cast', 'crew', 'release_date'])


#####################
films = pd.concat([pd.DataFrame([get_all_info(j)], columns=films.columns) for j in range(30)], ignore_index=True)
films.to_csv('data/movies/test.csv', sep='|', encoding='utf-8', header=True, index=False)
films = pd.read_csv('data/movies/test.csv', sep='|')
